### ISSUE TITLE
Mockenzo doesn't allow users to implement ready-made configuration objects within any method. 

### ISSUE THREAD

**Issue by SetropLeo** [CumbucaBr/mockenzo#11]
## Currently, we cannot use any ready-made objects within Mockenzo's Method.

For this reason, it isn't possible to organize our code in different files for different route contexts.

What I propose is to create a way that makes it possible to use objects (like the ones below) inside some Mockenzo's method. The method will get the data from the object and will create automatically the route configurations. 

<br>

### Example

1. Users create the objects.
```
const getProduct= {
  route: '/products',
  statusCode: 200,
  method: 'GET',
  delay: 1000,
  response: {
    status_code: '200',
    status_description: 'Good Get',
  },
};

const getWorkers= {
  route: '/workers',
  statusCode: 200,
  method: 'GET',
  delay: 1000,
  response: {
    status_code: '200',
    status_description: 'Good Get',
  },
};
```

<br>

2. They can create an array which will store all the objects.
```
const routes = [getProduct, getWorkers]
```

<br>

3. Now the user can use some both the object or the array itself inside the mockenzo method

- Using array constant: 
```
Mockenzo()
    .http()
        .on(3000)
        .run(routes)
        .start()
```

- Using any route object: 
```
Mockenzo()
    .http()
        .on(3000)
        .run(getWorkers)
        .start()
```

**Comment by charleston10** [comment]
https://github.com/CumbucaBr/mockenzo/pull/12
